name: update download branch

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2        
    - run: |
        git config --global user.email "chanyoungs@gmail.com"
        git config --global user.name "chanyoungs"
        git checkout download
        cd ..
        ls -a  