name: update download branch

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2        
      with:
        fetch-depth: 0
    - run: |
        cd ..
        ls -a
        # git config --global user.email "chanyoungs@gmail.com"
        # git config --global user.name "chanyoungs"
        # git checkout download
        # git merge main
        # python main.py
        # timestamp=$(cat "timestamp.txt")
        # git add .
        # git commit -m "${timestamp}"
        # git push