name: update download branch

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2        
      with:
        fetch-depth: 0
    - run: |
        git config --global user.email "chanyoungs@gmail.com"
        git config --global user.name "chanyoungs"
        python main.py
        git checkout download
        rm -r "Bulletins Templates"
        \cp -Rf "../output/." "./"
        ls -a
        timestamp=$(cat "timestamp.txt")
        git add .
        git commit -m "${timestamp}"
        git push